version: "3.9"

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123123"
      POSTGRES_DB: "salu"
      POSTGRES_USER: "salu_dev"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: on-failure
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: